# Generated by Django 3.2.6 on 2021-08-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nif', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('1', 'Transporter'), ('2', 'Operator')], default='1', max_length=60)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
