# Generated by Django 3.2.6 on 2021-08-19 10:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('province', models.CharField(max_length=60)),
                ('town', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'farm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('test', models.BooleanField()),
                ('volumn', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000000)])),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farm')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transporter')),
            ],
            options={
                'db_table': 'milkcollection',
                'managed': True,
            },
        ),
    ]
