# Generated by Django 3.2.6 on 2022-02-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollection',
            name='deliver',
            field=models.BooleanField(default=False),
        ),
    ]
