# Generated by Django 3.2.6 on 2022-03-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_milkcollection_deliver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkcollection',
            old_name='deliver',
            new_name='delivered',
        ),
    ]
