# Generated by Django 3.2.6 on 2021-08-19 10:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSilo',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[(1, 'Storage'), (2, 'Final')], default='1', max_length=60)),
            ],
            options={
                'db_table': 'finalsilo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReceptionSilo',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'receptionsilo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('final_silo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.finalsilo')),
                ('reception_silo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.receptionsilo')),
            ],
            options={
                'db_table': 'transfer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reception_silo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.receptionsilo')),
            ],
            options={
                'db_table': 'temperature',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('silo_dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silo_dst', to='plant.finalsilo')),
                ('silo_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silo_src', to='plant.finalsilo')),
            ],
            options={
                'db_table': 'changes',
                'managed': True,
            },
        ),
    ]
