# Generated by Django 3.2.6 on 2021-08-19 10:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('nif', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'transporter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MilkDelivery',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('test', models.BooleanField()),
                ('volumn', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000000)])),
                ('temperature', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('reception_silo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.receptionsilo')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transporter')),
            ],
            options={
                'db_table': 'milkdelivery',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('car_registration', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('tank_code', models.CharField(max_length=20)),
                ('current', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000000)])),
                ('current_volumn', models.IntegerField(blank=True, default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000000)])),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transporter')),
            ],
            options={
                'db_table': 'transport',
                'managed': True,
                'unique_together': {('car_registration', 'tank_code')},
            },
        ),
    ]
