# Generated by Django 3.2.6 on 2022-02-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkdelivery',
            old_name='reception_silo',
            new_name='silo',
        ),
    ]
