# Generated by Django 3.2.6 on 2022-02-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_rename_reception_silo_milkdelivery_silo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkdelivery',
            old_name='silo',
            new_name='reception_silo',
        ),
    ]
